In [65]:
def sortram(data,direction=1,deep=0):
    while deep<len(data):
        for i in range(len(data)+1)[1:-deep:direction]:
            a = data[i]
            b = data[i-1]
            if a<b:
                data[i] = b
                data[i-1] = a
        deep += 1
        sortram(data,direction,deep)
    return data

In [66]:
c=[1,3,6,2,8,11,12,3,5,8,2]
sortram(c)

[1, 2, 2, 3, 3, 5, 6, 8, 8, 11, 12]

In [72]:
import numpy as np
c = np.random.randint(low=1, high=20, size=20)
print(c)
sortram(c)


[ 4  7  6  6 13  9 17  9  2  9 14 16  1 10 16 10 18  6 13 19]


array([ 1,  2,  4,  6,  6,  6,  7,  9,  9,  9, 10, 10, 13, 13, 14, 16, 16,
       17, 18, 19])

In [82]:
def sortram1(data,direction=1,deep=0):
    while deep<len(data):
        for i in range(len(data)+1)[1:-deep:direction]:
            if data[i] < data[i-1]:
                data[i], data[i-1] = data[i-1], data[i]
        deep += 1
        sortram1(data,direction,deep)
    return data

In [83]:

sortram1(c)

array([ 2,  3,  3,  4,  4,  5,  5,  6,  9, 10, 11, 12, 14, 14, 16, 17, 17,
       18, 19, 19])

In [57]:

def sortelk(data,direction=1,top=0,bottom=1,smallest=None):
    while top<len(data):
        for i in range(len(data)+1)[bottom:-top:direction]:
            if smallest == None or data[i-1] < smallest:
                smallest = data[i-1]
            elif data[i-1]==smallest:
                bottom+=1
                smallest=None
            elif data[i] < data[i-1]:
                data[i], data[i-1] = data[i-1], data[i]
        top += 1
        sortelk(data,direction,top,bottom)
    return data



In [58]:
c=[1,3,6,2,8,11,12,3,5,8,2]
sortelk(c)

[1, 2, 2, 3, 3, 5, 6, 8, 8, 11, 12]

In [77]:
c = np.random.randint(low=1, high=20, size=20)
sortelk(c)

array([ 2,  2,  2,  5,  7,  8,  8, 11, 12, 14, 14, 14, 16, 17, 17, 17, 17,
       18, 19, 19])

In [78]:

c = np.random.randint(low=1, high=20, size=20)
def wrapper(func, *args, **kwargs):
    def wrapped():
        return func(*args, **kwargs)
    return wrapped



In [80]:
import timeit
wrapelk = wrapper(sortelk,c,direction=1,top=0,bottom=1,smallest=None)
timeit.timeit(wrapelk,number = 5)


5.38550946200121

In [81]:
import timeit
wrapram = wrapper(sortram,c,direction=1,deep=0)
timeit.timeit(wrapram,number = 5)



12.559534374999203

In [84]:
import timeit
wrapram1 = wrapper(sortram1,c,direction=1,deep=0)
timeit.timeit(wrapram1,number = 5)

12.123437879999983

In [99]:
import timeit
d = c.sort
timeit.timeit(d,number = 5)

0.00023136799973144662

Woah. That's Fast.